name: Releasability status
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]  # Name must match the build workflow
    types:
      - completed
    branches:
      - master
      - branch-*

jobs:
  update_releasability_status:
    runs-on: sonar-xs
    name: Releasability status
    permissions:
      id-token: write
      statuses: write
      contents: read
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@v3
        with:
          optional_checks: "Jira,CheckDependencies"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
